apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails-example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: duleorlovic/kubernetes-rails-example:latest
        ports:
        - containerPort: 3000
        env:
          - name: EXAMPLE
            value: defined in kubernetes yml
          - name: REDIS_URL
            value: redis
          - name: REDIS_PORT
            value: "6379"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-secrets
                key: rails_master_key
