apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: duleorlovic/kubernetes-rails-example:latest
        command: ['sidekiq']
        env:
        - name: REDIS_URL
          value: redis://redis.default.svc.cluster.local:6379/
